# Server and Database Config
server.port=8084
spring.datasource.url=jdbc:mysql://localhost:3306/patients-db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# JPA/Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Schema Initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Date Format and Thymeleaf
spring.mvc.format.date=yyyy-MM-dd
spring.thymeleaf.cache=false
